version: '3'
services:
  app:
    env_file:
      - .env
    container_name: golang
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
    tty: true
    build:
      context: .
    ports:
      - '${APP_PORT:-80}:80'
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - net
  postgres:
    env_file:
      - .env
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - 'pgsql:/var/lib/postgresql/data'
    networks:
      - net
networks:
  net:
    driver: bridge
volumes:
  pgsql:
    driver: local